language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: YlamWtBmrW4agUHWm5hibdxLLqju/7D1C31clvWVLrwP5m0AvZHGocNgOxfV+BR4revk6pfcEhOUHjIPXW9LS2ePxvg/pp16fErC7OYgGAD6zCVnxluMUZr69tfK1+aZA5AU9zstaK6mZAggiRA2OP68eFyKzKfXtqKAO6Xi5JexhdJ4MTDluesyLQJcDSfWoL6MzbLy4L6/KiBK2pjIb8+uGwyHjHaXmOoGDMXQoECmYls7OHR3Lp1javs2umk0FfW9P+8McUFEAocVRldOLemmDT5pzfiEWGzIjTFq6I6BkJeQbuJPjQn2nEA9DIQ1nUyNAcYQw22VsEcvIOriT6GlzEET/YAhuNOkLcBg0E84U+xLKP1joPlTyY2quUzgl/ZxyHLe5zVd606iRcNbDeng2LAP1wScW/ukdNN+ap7U2We/JLPzQEGS2s4vKYjIvtmk8qaXQp7lg5AYnTHYK5cvc+fmk9fFGTB/uQtXBzHD5vlTNl5lVevvWY1prv226W6dssMbweUhK1aQixCGf7TJPNNYFa45/JcGcGkZ6mmPLgrPbE3ZLO7plkv4Jj52IJ0LQWCh76gxlqgfcQiYq8QTIIgY8tmETzVRQQeCaAKZRmomtdY1ZNER9IlJUoXUUJ/R7tGHGiSqPw15cICoAtfv58y2VzISdkek9l0iHNM=
  app: a-simon-game
  on:
    repo: HebaNAS/a-simon-game
